Algoritmo "atvd1"
// Disciplina   : [ Lógica de Programação ]
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/11/2021
Var
x1:inteiro

Inicio
repita
 escreval("----------MENU----------")
 escreval("1 - cadastrar ")
 escreval(" 2 - Adicionar")
 escreval(" 3 - Excluir")
 escreval(" 0 - SAIR!")
 escreval("------------------------")
 leia(x1)
 limpatela
 ate (x1 = 0)

Fimalgoritmo